### ISSUE TITLE
Editor pane does not display on MacOS Safari 

### ISSUE THREAD

**Issue by whaley** [swagger-api/swagger-editor#1232]
Safari Version: 10.0.3 (12602.4.8)
MacOS Version: 10.12.3 (16D32)
Git Commit: 400ebdb3 (recreated on the v3.0.1 and v3.0.0 tags also)

See attached screenshot for an example of what I'm referring to. 

Tangentially, there is an issue with rendering the arrows on the opblock-tag styled drop down lists that is also apparent in my screenshot.

Everything seems to work correctly on Chrome.

<img width="1205" alt="screen shot 2017-03-23 at 8 21 36 am" src="https://cloud.githubusercontent.com/assets/166648/24247373/d85b49ac-0fa1-11e7-8043-ac1d229dfaec.png">

**Comment by webron** [comment]
Should be fixed in master.

**Comment by whaley** [comment]
After merging from master to make my HEAD 6153efc533dd0f33de1670f43064ce9525e82d15, I still see the same behavior.   @Minasokoni if you need any more details from me, let me know.

**Comment by Minasokoni** [comment]
@whaley Did you run the command `npm run build` I see in your screenshot you are showing the prebuilt dist files

**Comment by whaley** [comment]
@Minasokoni I did, but with node version 7.  @webron has already updated the readme to reflect that node version 6 is required.  Once I used `nvm exec 6 npm run build` and then opened index.html in Safari, everything worked as expected with the editor appearing.

**Comment by Minasokoni** [comment]
@whaley Excellent!
