### ISSUE TITLE
Callback pane does not expand 

### ISSUE THREAD

**Issue by rranade** [swagger-api/swagger-editor#1565]
I loaded the official OpenAPI 3.0 example for callbacks (https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/callback-example.yaml) into the Swagger Editor hosted at http://editor.swagger.io. A callbacks tab correctly shows up and shows a "POST" box for the callback, but clicking on the callback box does nothing - I would have expected that box to expand and show some of the other data specified in the YAML. Tried this on multiple browsers with the same result. Is this box supposed to expand?

**Comment by shockey** [comment]
This is fixed over in Swagger-UI.

Thanks for the report, @rranade!

**Comment by x00x70** [comment]
I'm still seeing issues with this.  The callback tab works, but the details inside the callback request just load indefinitely:
<img width="677" alt="screen shot 2018-02-28 at 11 36 09" src="https://user-images.githubusercontent.com/25639550/36785707-9f932e5e-1c7b-11e8-89f6-efa58ecc2f6f.png">

**Comment by webron** [comment]
@shockey this needs to be addressed.

**Comment by shockey** [comment]
This is fixed! 🎉
