### ISSUE TITLE
Security requirements must match a security definition

### ISSUE THREAD

**Issue by xjurcak** [swagger-api/swagger-editor#1604]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |   Bug
| Which Swagger/OpenAPI version?      | 3.0.0
| Which Swagger-Editor version?       |  Online version http://editor.swagger.io/
| How did you install Swagger-Editor? |  Online version http://editor.swagger.io/
| Which broswer & version?            |   Google Chrome Version 63.0.3239.84 (Official Build) (64-bit)
| Which operating system?             |  Winodows 10 Home

### Demonstration API definition

```openapi: 3.0.0
info:
  description: This is api specification for SurgLogs Resource server
  version: 1.0.3
  title: SurgLogs Api
servers:
  - url: 'http://devel.surglogs.mofa.sk/api/v5'
paths:
  /something:
    get:
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Success
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'

```

### Expected Behavior
 No errors in swagger editor

### Current Behavior
 swagger editor shows error for provided api.
```
Semantic error at paths./something.get.security.0
Security requirements must match a security definition
Jump to line 12
```

**Comment by shockey** [comment]
Hi @xjurcak! This was fixed in 3.2.1, but we're having problems redeploying editor.swagger.io :confused: it should be resolved tomorrow!

**Comment by shockey** [comment]
Deployed! This should be fixed :smile:

**Comment by HristiyanZahariev** [comment]
Hello, I know this issue is closed but I still have the same problem in: http://editor.swagger.io/ . Date: 27.02.2018

**Comment by renatoargh** [comment]
I have this problem when I use a dash on the security definition name:

![image](https://user-images.githubusercontent.com/522043/36937432-f9c99980-1ef1-11e8-918e-8935a2fdfa4f.png)

The problem goes away when I remove the dash:

![image](https://user-images.githubusercontent.com/522043/36937440-11de3cb0-1ef2-11e8-937c-02ea31ac25a1.png)

**Comment by charlescapps** [comment]
I'm seeing this as well for a Swagger 2.0 file when the security name has dashes in it.

**Comment by andy193** [comment]
The problem still persists in Swagger 2.0 as now. I have the exact same API specs as OP's. Could any one of help?

**Comment by hkosova** [comment]
@andy193 please open a new issue and fill in the details in the template.

**Comment by b-hayes** [comment]
IM having the same problem now. Exactly the same definition as OP.
```
security:
        - BearerAuth: []
```
If there is a more recent issue opened please link it so I can jump on that one.

**Comment by yasirjanjua** [comment]
@b-hayes I am facing the same issue
