### ISSUE TITLE
Reference object ($ref) in Path or Operation Object throws error in Swagger editor

### ISSUE THREAD

**Issue by shengt** [swagger-api/swagger-editor#1605]
Reference object `$ref` in Path or Operation Object throws error in Swagger editor

| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | 3.0.0
| Which Swagger-Editor version?       | Online version http://editor.swagger.io/
| How did you install Swagger-Editor? | Online version http://editor.swagger.io/
| Which broswer & version?            | Firefox 57.0.1
| Which operating system?             | Mac OS X 10.13.2

### Demonstration API definition
```yaml
openapi: 3.0.0
info:
  title: Simple API overview
  version: 'v1'
components:
  parameters:
    id2Param:
      name: id2
      in: path
      required: true
      schema:
        type: string
paths:
  /{id2}/{id}:
    parameters:
      - $ref: '#/components/parameters/id2Param'
      - name: id
        in: path
        description: The id
        required: true
        schema:
          type: string
          format: uuid
    get:
      summary: List API versions
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                type: object
```

### Expected Behavior
No errors in swagger editor

### Current Behavior
swagger editor shows error for `id2` parameter in the provided api.
```
Semantic error at paths./{id2}/{id}
Declared path parameter "id2" needs to be defined as a path parameter at either the path or operation level
Jump to line 14
```

**Comment by shockey** [comment]
Thanks for the report, @shengt!

This was fixed in 3.2.1, but we're having problems redeploying the online Editor service (cc #1604). This should be resolved in the next day or so!

**Comment by shockey** [comment]
Deployed! This should be fixed :smile:

**Comment by filipsuk** [comment]
@shockey this seems to be still a problem on https://editor.swagger.io/

```
Semantic error at paths./users/{service-name}/add-auth-code
Declared path parameter "service-name" needs to be defined as a path parameter at either the path or operation level
Jump to line 12
```

```yaml
swagger: '2.0'
info:
  version: 1.0.0
  title: Example
basePath: /api/v1
tags:
  - name: users
schemes:
  - https

paths:
  /users/{service-name}/add-auth-code:
    post:
      tags:
        - users
      summary: Send a user's OAuth2 authorization code for the given service
      consumes:
        - application/json
      parameters:
        - $ref: "#/parameters/service-name"
        - in: body
          name: body
          description: OAuth2 authorization code
          required: true
          schema:
            type: object
            properties:
              user_id:
                type: string
              auth_code:
                type: string
        
      responses:
        204:
          description: success

parameters:
  service-name:
    name: service-name
    description: Data provider service name
    in: path
    type: string
    required: true
```

**Comment by shockey** [comment]
@filipsuk yep, it is - we're tracking that in https://github.com/swagger-api/swagger-editor/issues/1614, and should have it fixed this week 😄
