### ISSUE TITLE
use of $ref in paths parameters errors for "in: path" parameters

### ISSUE THREAD

**Issue by wol190** [swagger-api/swagger-editor#1614]
An error message is currently generated when using $ref for in: path (in: query and in: body work fine) parameters from within the paths description, e.g. - $ref: '#/parameters/tag-name', where tag-name appears in the path, e.g. /tags/{tag-name}:

| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | swagger 2.0
| Which Swagger-Editor version?       | http://editor.swagger.io/ (but not http://editor2.swagger.io)
| How did you install Swagger-Editor? | online editor
| Which browser & version?            | Tried Chrome and Firefox, same error in both cases
| Which operating system?             |  Windows

Example extracted from the Instagram API example file:

```
swagger: '2.0'

info:
  version: v1
  title: Instagram API
host: api.instagram.com
basePath: /v1
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json

parameters:
  tag-name:
    name: tag-name
    in: path
    description: Tag name
    type: string
    required: true
paths:
  /tags/{tag-name}:
    parameters:
      - $ref: '#/parameters/tag-name'
    get:
      description: Get information about a tag object.
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Tag'
definitions:
  Tag:
    type: object
    properties:
      media_count:
        type: integer
      name:
        type: string
```

This results in the following error:

Semantic error at paths./tags/{tag-name}
Declared path parameter "tag-name" needs to be defined as a path parameter at either the path or operation level
Jump to line 23

However, the UI recognises what the tag-name is and allows the "Try it out" operation to be performed

To avoid the error, the parameter definition can be brought in-line (see below), but this is undesirable if many operations reference the same parameter.

```
paths:
  /tags/{tag-name}:
    parameters:
      - name: tag-name
        in: path
        description: Tag name
        type: string
        required: true
```

**Comment by gitforpushpak** [comment]
@shockey May I know the fix release date please ?

**Comment by wol190** [comment]
Thanks for the issue references - I'd only searched on open issues when raising this, but thankfully raising this separately has turned out to be appropriate

**Comment by shockey** [comment]
@gitforpushpak I'm expecting to get a fix out tomorrow evening 😄

**Comment by shockey** [comment]
This is fixed. Thanks @wol190!

**Comment by wol190** [comment]
I'm afraid that I'm still experiencing the same issue, even running the editor locally. From what I can see the error message is being triggered from within .\dist\swagger-editor-bundle.js, specifically from within t.validatePathParameterDeclarationHasMatchingDefiniton: "else s.found||e.push({message:'Declared path parameter "'+o+'" needs . . ."

**Comment by shockey** [comment]
@wol190, is this with the API definition that you provided in the original issue filing?

If so, I'm not able to reproduce it. Do note that the `dist/` files in the repository are stale, since they're only updated during releases. You'll need to clone the project and run a development server in order to work with the latest changes.

Let me know!

**Comment by wol190** [comment]
@shockey, thanks for getting back to me. This is what I see using https://editor.swagger.io/

![image](https://user-images.githubusercontent.com/8318503/34618999-827cc1bc-f238-11e7-99da-5c40640b71fe.png)

To run locally, I cloned the swagger-editor repository and used npm start to fire up the http-server at http://127.0.0.1:3001. I then edited swagger-editor-bundle.js to change the error message and restarted, after which my changes were reflected in the error message. However, I presume from your comments, that my local dist files are stale.

**Comment by wol190** [comment]
@shockey Now using npm run dev to start up development server the error disappears :-)
