### ISSUE TITLE
References to remote files not supported?

### ISSUE THREAD

**Issue by glipman** [swagger-api/swagger-editor#1702]
When I use the following fragment at http://editor.swagger.io/ I get a semantic error: `$ref paths must begin with '#/'`
```json
{
   "openapi":"3.0.0",
   "info":{
      "description":"This is a test API definition",
      "version":"2017.3",
      "title":"API2 test",
      "termsOfService":"http://swagger.io/terms/"
   },
   "servers":[
      {
         "url":"http://test.lokalhost/myapi2/",
         "description":"This environment"
      }
   ],
   "paths":{
      "/myobjects":{
         "$ref":"http://example.com/myobjects.swagger.json"
      }
   }
}
```
Are references to remote files no longer supported?
Maybe the editor does not support them but that does not make them a semantic error?

**Comment by webron** [comment]
@glipman - that's... an unfortunate regression unfortunately which we'll fix shortly. The mistake is in the validation itself, not the remote reference. You can keep using those.

**Comment by shockey** [comment]
this is fixed - sorry for the inconvenience @glipman!

**Comment by BrenBarn** [comment]
I still can't really understand what the status of this is.  I'm only using the web editor at https://editor.swagger.io/ --- no local install of any swagger tools.  As far as I can tell, relative `$ref` doesn't work at all.  (I get "Could not resolve reference: Tried to resolve a relative URL, without having a basePath".)  Is the online editor just going to stay broken like that?

**Comment by shockey** [comment]
@BrenBarn, the Editor is unable to resolve relative references (e.g. `$ref: "./doc1.yaml#/definitions/Abc"`) because the top-level document (the one you write in the Editor) has no associated URL, since it's just text content in the Editor.

Remote references are fine, but you'll need to add full URLs to your references so that the Editor's subsystems know where to look for your documents.

**Comment by fredwangwang** [comment]
Unfortunately, it is still an issue on swagger editor. Tried both online version and docker.

![image](https://user-images.githubusercontent.com/21690857/65820535-98471100-e1e7-11e9-8848-758c829a21e5.png)

**Comment by webron** [comment]
@fredwangwang checking the original definition, the issue is not reproduced. If you are able to reproduce the issue, it may be slightly different. Please make sure you're using the latest version of the Editor. If you're using the latest and can reproduce it, please file a new issue following the issue template.

**Comment by carlocaprini** [comment]
I am also still experiencing this issue while in swagger editor and trying to use an absolute url (`https://....`).
```
Semantic error at paths./app.post.requestBody.content.application/json.schema.$ref
$ref paths must begin with `#/`
```
