### ISSUE TITLE
allOf doesn't render in the UI

### ISSUE THREAD

**Issue by skullmaggots** [swagger-api/swagger-editor#272]
Trying to create a model that uses composition with allOf in the editor like so....

````
  Event:
    discriminator: name
    properties:
      name:
        type: string
    required:
      - name
      
  ReferAFriendEvent:
    allOf:
      - $ref: Event
      - properties: 
          accountId:
            type: integer
          campaignname:
            type: string
````

However the UI just displays an empty list for the ReferAFriendEvent.
Not sure whether this is a bug or composition not supported in the editor UI yet.

**Comment by freak4pc** [comment]
Is there any progress with this? :)

**Comment by mohsen1** [comment]
This was fixed from upstream 

![screen shot 2015-04-22 at 4 20 27 pm](https://cloud.githubusercontent.com/assets/543633/7287633/905b2ae6-e90b-11e4-9561-b6cc812cf637.png)

**Comment by bagofjuice** [comment]
Rendering still doesn't work if it's part of a properties object (shows as empty in view):
```
swagger: '2.0'
info:
  version: 0.0.3
  title: API
paths:
  /system:
    get:
      summary: some text
      responses:
        '200':
          description: Successful Operation
          schema:
            type: object
            properties:
              id:
                type: string
              type:
                type: s
              attribtues:
                allOf:
                  - type: object
                    $ref: '#/definitions/a'
                  - type: object
                    $ref: '#/definitions/b'
definitions:
  a:
    properties:
      propertyX:
        type: string
  b:
    properties:
      propertyY:
        type: string
```



But this works ok:
```
swagger: '2.0'
info:
  version: 0.0.3
  title: API
paths:
  /system:
    get:
      summary: some text
      responses:
        '200':
          description: Successful Operation
          schema:
            type: object
            allOf:
              - type: object
                $ref: '#/definitions/a'
              - type: object
                $ref: '#/definitions/b'
definitions:
  a:
    properties:
      propertyX:
        type: string
  b:
    properties:
      propertyY:
        type: string
```

**Comment by mohsen1** [comment]
@bagofjuice that issue has moved here https://github.com/swagger-api/swagger-editor/issues/476
