### ISSUE TITLE
Can only access editor at 127.0.0.1:9000 not at host.domain:9000

### ISSUE THREAD

**Issue by DavidBiesack** [swagger-api/swagger-editor#294]
This worked when I last tried it a few weeks ago, but now I can only access swagger-editor via http://127.0.0.1:9000 , not by my actual desktop's fully qualified hostname (http://djb.na.sas.com:9000 on our intranet). Both Google Chrome and Firefox return errors such as 

     Google Chrome's connection attempt to djb.na.sas.com was rejected. The website may be down, or your network may not be properly configured.

I don't recall doing any network or other configuration changes. This is running on Linux (Ubuntu 14.10) 

Note: I recently did a full stop of npm/node processes, performed a 'git pull', 'grunt build' (successful) and restarted my swagger-editor with 'npm start'. again, running on 127.0.0.1:9000 works fine. Other services such as cors-it are running fine on my djb.na.sas.com (on other ports).

Has something changed recently with swagger-editor to restrict it to 127.0.0.1? I'd like other folks on our team to use swagger-editor that I'm running.

**Comment by mohsen1** [comment]
I don't think we changed anything in that regard. [the URL option is here](https://github.com/swagger-api/swagger-editor/blob/master/grunt/connect.js#L4).

**Comment by DavidBiesack** [comment]
Thanks, I was able to change this to djb.na.sas.com and the editor now works as expected. Can you add a note about this to the 'Running Locally' section on README.md?

**Comment by mohsen1** [comment]
@DavidBiesack `localhost` can be inaccessible form a process. It's a permission issue and should be resolved by system configurations. The fix you did works but I rather fixing system/process permissions.

**Comment by DavidBiesack** [comment]
any pointers on what to configure? I'm not a system or network administrator. Whatever you can do to make installing/configuring/using the swagger tools easier for all potential users, the better. Thanks.

**Comment by mingfang** [comment]
this is still a problem, isn't it?
I need to be able to access the editor from the network and not from localhost

**Comment by mingfang** [comment]
Never mind.
I'm using swagger-node and the command ```swagger project edit --host '0.0.0.0'``` works.

**Comment by cacti77** [comment]
The magic line now seems to be https://github.com/swagger-api/swagger-editor/blob/master/server.js#L7 . This really ought to be documented better or made more easily configurable (just like PORT is now?) because I would've thought wanting to access the Swagger Editor from another machine is a very common use case.
