### ISSUE TITLE
Swagger editor won't put false boolean values in the URL for "try this operation" 

### ISSUE THREAD

**Issue by Syzygy24** [swagger-api/swagger-editor#542]
The segment in question is

``` yaml
parameters:
          name: debug
          in: query
          description: |
            Parameter must be included as part of the URI. If set to true, ERROR
            message will return full entity response message.
            ** keep off if performance is a consideration **
          required: false
          type: boolean
          default: false
          allowEmptyValue: false
```

Our api won't allow requests with an empty debug value. I would just like to be able to pass "false" in, but nothing I tried will allow it. Changing it to true makes it work just fine, but there are performance considerations with that feature. Changing the value to false in the dropdown menu just makes it an empty string rather than false and the response returns an error because we passed in an empty value for debug.

GET http://{url}/v1/stores?debug= HTTP/1.1

Adding "allowEmptyValue: false", changing required to true, and adding "default: false" haven't helped.
Is there a way around this?

**Comment by mohsen1** [comment]
If it's not required why it should be in the URL?

**Comment by emrehan** [comment]
It doesn't put false boolean values into bodies neither.

**Comment by tabetan** [comment]
Hi, is this problem fixed? WHen will it be fixed? I am experiencing the same problem.

**Comment by mkrufky** [comment]
I am also seeing this problem using editor.swagger.io today 2016-01-01

**Comment by jwthomp** [comment]
I am hitting this as well.

Is this desired behavior by Swagger for some reason?

**Comment by fehguy** [comment]
No, this is a bug.  We're working on it, but it's caused deep in one of the dependencies.  We'll close this out when it's addressed (I know, it's annoying).

**Comment by jwthomp** [comment]
@fehguy That's great, thank you for the update and answer.

**Comment by puncha** [comment]
Are you still working on this bug? It makes my API not work properly.

**Comment by saharj** [comment]
I guess this issue has been fixed now. Would anyone take a moment and test it please?

**Comment by ralfhandl** [comment]
Just tested it after fresh fetch, rebase, and install, and the issue is still there. Can get $count=true into the URL but not $count=false. Which doesn't bother me because omitting $count is equivalent to $count=false in my APIs :-)

**Comment by saharj** [comment]
I have difficulties understanding the issue.

Here's the code I use:

```
---
swagger: '2.0'
info:
  version: "1.0.0"
  title: Basic Auth Example
host: basic-auth-server.herokuapp.com
schemes:
  - http
  - https
paths:
  /:
    get:
      responses:
        200:
          description:  ok
      parameters:
        - name: debug
          in: query
          description: Parameter must be included as part of the URI.
          required: false
          type: boolean
          default: false
          allowEmptyValue: false
```
And here's my preview:
<img width="693" alt="screen shot 2016-04-21 at 2 07 19 pm" src="https://cloud.githubusercontent.com/assets/1468463/14724364/7a2c775a-07ca-11e6-87da-b8bc39e21e5b.png">

I get that there is an error in the preview that shows `required: true` even though we set it to be `false`. But other than that I don't understand what the problem is. Can you please help me @ralfhandl ?

**Comment by puncha** [comment]
I also did the test, the bug is still there. Different from ralfhandl, it bothers me a lot. It is not possible for me to re-design my API to walk around this bug.

**Comment by saharj** [comment]
This is a dependency issue: https://github.com/jdorn/json-editor/issues/406

**Comment by jpetitte** [comment]
can confirm I am still hitting this issue.

**Comment by jenswachtel** [comment]
Same here. I wish that would be possible. It doesn't show the properties in the model example list.

**Comment by webron** [comment]
@jenswachtel do you experience that with the 3.x editor?

**Comment by webron** [comment]
Closing as should be fixed. File a new ticket if not.

**Comment by zoharsanchez** [comment]
@webron The issue still persists for me. I even checked out the http://editor2.swagger.io/#!/ to check if it's a user error on my end, but it seems that by making the following change:
```  - name: latitude
          in: query
          description: Latitude component of location.
          required: true
          type: boolean```

When selecting false, it does not appear in the query (I am trying to put the boolean in the body). Unfortunately, for me it's essential that I use a boolean...if I change the type to string, it works, but only if the user inputs either true or false (and that is prone to error - "tue", "fasle", etc.).

Perhaps this has already been fixed or there is a workaround? :) Thanks!

**Comment by webron** [comment]
@zoharsanchez tested it with the current editor, and it sends the query parameter just fine...

**Comment by zoharsanchez** [comment]
@webron Hmmm, that's strange, I'm still getting the error...I made the same change as above and when I click on `false`, I get this for the query: `GET https://api.uber.com/v1/products?latitude=&longitude= ` versus if I put in `true`: `GET https://api.uber.com/v1/products?latitude=&longitude=true`

**Comment by webron** [comment]
Which version of the editor do you use?

**Comment by zoharsanchez** [comment]
@webron 2.0, same as that in http://editor2.swagger.io/#!/

**Comment by shockey** [comment]
@zoharsanchez, this bug may still exist in the 2.x series of the editor, as that series is no longer under development. If you use editor version 3 (found at http://editor.swagger.io/), you should be clear of this problem 😄

**Comment by zoharsanchez** [comment]
@shockey Awesome, thank you for pointing that out! I'll upgrade the version to get outta this limbo! :) Cheers!
