### ISSUE TITLE
Editor cannot send request with file

### ISSUE THREAD

**Issue by hantuzun** [swagger-api/swagger-editor#599]
Hi,

We have an endpoint with the following parameters:

```
      parameters:
        - name: upload
          in: formData
          required: true
          type: file
```

I wanted to try the endpoint using the editor. I choose a file on the editor, set the header and then hit the "send request".

However, the editor doesn't send the file content. The following is the body is being send by the editor:

```
(upload: actions.csv)
```

Whereas a proper request should have such a body:

```
(--------------------------a1c5ec12084324b4 
Content-Disposition: form-data; name="upload"; filename="actions.csv" 
Content-Type: application/octet-stream 
 "230", "969",  4 "90",  "1101", 4 "276", "234",  5 "325", "168",  3 "15",  "754",  5 "324", "298",  5 "73",  "48",   2 "232", "315",  5 "328", "98",   4 "128", "588",  5 
 --------------------------a1c5ec12084324b4--)
```

Could you confirm that this issue about the swagger-editor?

**Comment by mohsen1** [comment]
For now, file only in body is supported.

**Comment by webron** [comment]
@mohsen1 - as the spec defines it, `file` is only supported with `formData`, not `body`. This is a bug.

**Comment by emrehan** [comment]
Yes @webron, I was about to point this out.

**Comment by mohsen1** [comment]
@webron is this the only way to have file parameters in Swagger?

**Comment by webron** [comment]
Of type `file`? Yes.

**Comment by saharj** [comment]
Moving it to next milestone.

**Comment by saharj** [comment]
I think this issue has been fixed.

**Comment by suyuan1203** [comment]
this bug is still not fixed because the code calls $.ajax with Content-Type as 'application/json'.

scripts/controllers/tryoperation.js

makeCall function
`
$.ajax({
      url: $scope.generateUrl(),
      type: $scope.operationName,
      headers: _.omit($scope.getHeaders(), omitHeaders),
      data: $scope.getRequestBody(),
      contentType: $scope.contentType,
      processData: false
    })
`
the contentType property should be set as false.

> When sending data to the server, use this content type. Default is "application/x-www-form-urlencoded; charset=UTF-8", which is fine for most cases. If you explicitly pass in a content-type to  $.ajax(), then it is always sent to the server (even if no data is sent). As of jQuery 1.6 you can pass false to tell jQuery to not set any content type header. Note: The W3C XMLHttpRequest specification dictates that the charset is always UTF-8; specifying another charset will not force the browser to change the encoding. Note: For cross-domain requests, setting the content type to anything other than application/x-www-form-urlencoded, multipart/form-data, or text/plain will trigger the browser to send a preflight OPTIONS request to the server.
