### ISSUE TITLE
swagger editor does not handle optional query parameters

### ISSUE THREAD

**Issue by wjblazek** [swagger-api/swagger-editor#684]
I’ve searched all the posts here and elsewhere and don’t see this issue addressed anywhere.
The swagger editor does not appear to handle optional query parameters correctly.
When parameters are listed as required: false in the parameter list, 
the Try this operation UI always includes them in the send request with no values instead of leaving them out of the request.
There does not appear to be a way to send a request that does not include optional query parameters.
Is this a known issue?

I have an API to do these operations:
GET http://somehost/v1/xyz                                                      # GETs all things
GET http://somehost/v1/xyz?parm1=value1                             # GETs all things filtered by param1
GET http://somehost/v1/xyz?parm2=value2                             # GETs all things filtered by param2
GET http://somehost/v1/xyz?parm1=value1&parm2=value2    # GETs all things filtered by param1 and param2

But the Try this operation UI will only do the last operation, 
GET http://somehost/v1/xyz?parm1=value1&parm2=value2
even though the 2 query parameters are optional.
It will not do the 1st 3 operations: without either optional parameter or with only one of them.
I also tried the allowEmptyValue: true attribute without success.

```yaml
  /xyz:
    get:
      tags:
        - xyz URL01 
      summary: All xyz Messages 
      description: Provides All xyz Messages for the given Account ID.
      parameters:
        - name: AccountId
          in: header
          description: User Authorization
          required: true
          type: string
          format: int10
        - name: parm1
          in: query
          description: parm1
          required: false
          type: string
          format: int10
          allowEmptyValue: true
        - name: parm2
          in: query
          description: parm2
          required: false
          type: string
          format: int10
          allowEmptyValue: true
```

I also tried splitting out the URLs and it still does the same thing.
The Try this operation UI for URL01 below pulled in the parameters from the other URLs, 2,3,4.

```yaml
 /xyz:
    get:
      tags:
        - xyz URL01 
      summary: All xyz Messages 
      description: Provides All xyz Messages for the given Account ID.
      parameters:
        - name: AccountId
          in: header
          description: User Authorization
          required: true
          type: string
          format: int10

 /xyz:
    get:
      tags:
        - xyz URL02 
      summary: All xyz Messages 
      description: Provides All xyz Messages for the given Account ID.
      parameters:
        - name: AccountId
          in: header
          description: User Authorization
          required: true
          type: string
          format: int10
        - name: parm1
          in: query
          description: parm1
          required: false
          type: string
          format: int10
          allowEmptyValue: true
 
/xyz:
    get:
      tags:
        - xyz URL03 
      summary: All xyz Messages 
      description: Provides All xyz Messages for the given Account ID.
      parameters:
        - name: AccountId
          in: header
          description: User Authorization
          required: true
          type: string
          format: int10
        - name: parm2
          in: query
          description: parm2
          required: false
          type: string
          format: int10
          allowEmptyValue: true

xyz:
    get:
      tags:
        - xyz URL04 
      summary: All xyz Messages 
      description: Provides All xyz Messages for the given Account ID.
      parameters:
        - name: AccountId
          in: header
          description: User Authorization
          required: true
          type: string
          format: int10
        - name: parm1
          in: query
          description: parm1
          required: false
          type: string
          format: int10
          allowEmptyValue: true
        - name: parm2
          in: query
          description: parm2
          required: false
          type: string
          format: int10
          allowEmptyValue: true
```

Is this a known problem?
Thanks!

**Comment by jeff9finger** [comment]
I am having this same issue.

**Comment by smartpunter** [comment]
Same for me

**Comment by nbonnotte** [comment]
Same for me

**Comment by nbonnotte** [comment]
I've just made a pull request for a quick-and-dirty solution.

**Comment by stefanhendriks** [comment]
+1

**Comment by shekhar-jha** [comment]
+1

**Comment by Thomasmnielsen** [comment]
Would be nice to get this fixed.

**Comment by saharj** [comment]
This issue was fixed here: #706
Please try it out again and let us know if there is any issue.

**Comment by tommyjcarpenter** [comment]
@saharj  I am still having this issue with the default swagger editor at swagger.io. 

My yaml was:
```
swagger: "2.0"
info:
  version: "0.1.0"
  title: "..."
paths:
  /tenant/{vmname}:
    get:
      tags:
      - "default_controller"
      description: "..."
      operationId: "controllers.default_controller.tenant_vmname_get"
      parameters:
      - name: "vmname"
        in: "path"
        description: "Key into A&AI"
        required: true
        type: "string"
      - name: "fieldlist"
        in: "query"
        description: "Optional list of fields for server side filtering"
        required: false
        type: "string"
        format: "field1+field2+..."
      responses:
      ...
```
   
But the code that was generated was:
```
def tenant_vmname_get(vmname, fieldlist) -> str:
    return 'do some magic!'
```

Which is *wrong*, because the fieldlist parameter was optional. 

It should have been something like:
```
def tenant_vmname_get(vmname, fieldlist=None) -> str:
    return 'do some magic!'
```

**Comment by saharj** [comment]
@tommyjcarpenter This is a code-gen issue.

**Comment by tommyjcarpenter** [comment]
@saharj aye, sorry for the mispost.

**Comment by saharj** [comment]
@tommyjcarpenter No worries.
