### ISSUE TITLE
Definition 'undefined' error in Preview

### ISSUE THREAD

**Issue by showwin** [swagger-api/swagger-editor#782]
Hello, :smiley: 
After the commit 7e0b15a, the specific `definition` name is displayed `undefined` in Preview.
<img width="712" alt="screen shot 2016-01-20 at 16 55 06" src="https://cloud.githubusercontent.com/assets/1732016/12442827/a3a5a9a2-bf96-11e5-86bd-39087ac16a7e.png">

In particular, if the definition name includes other definition's name, it is displayed as `undefined`. (example YAML is in bottom)

As I mentioned, this bug is from the difference of `sway-worker` v1.8.0 and v1.10.0. But [the difference of v1.8.0 to v1.10.0](https://github.com/mohsen1/sway-worker/compare/662dca57c3c94f6d825b848aa6c7bdcd37fec62f...master) looks too big to find the root cause of bug...
Therefore, I suggest to revert `sway-worker` v1.8.0.

Here is a sample YAML
```yaml
swagger: '2.0'
info:
  title: same string error
  version: 0.1.0
host: api.sample.com
schemes:
  - https
basePath: /api/v1
produces:
  - application/json
paths:
  /test:
    get:
      responses:
        default:
          description: this is undefined
          schema:
            $ref: '#/definitions/sameStringHere_plus_foo'
definitions:
  sameStringHere_plus_foo:
    type: object
    properties:
      here:
        $ref: '#/definitions/sameStringHere'
  sameStringHere:
    type: object
    properties:
      foo:
        type: integer
```

**Comment by kogai** [comment]
For reference...

`sway-worker` dependent to `json-refs` modules.
(it seems to be after build some own code with webpack)

And latest release of `json-refs` resolve reference name includes own definitions name as circular erroneously.

It already fixed, and reviewing now.

**Comment by saharj** [comment]
Yes, this issue had happened because sway has changed its API (https://github.com/apigee-127/sway/issues/59) and sway-worker was working with the old API. The issue is fixed on the new version of sway-worker.
I made a pull request to fix this.

**Comment by showwin** [comment]
@saharj Thank you for updating sway-worker, LGTM :+1: 

I close my PR.

**Comment by showwin** [comment]
@saharj I'd mentioned to close my pull request #783. I think this issue should be kept open until merge your pull request #787. This problem is not fixed.

**Comment by MrWhiski** [comment]
Is this problem still not fixed? 'Caus I have the same issues right now.

**Comment by saharj** [comment]
@MrWhiski Please make sure you are using the latest version of Swagger Editor, and then let us know if you still have this issue.

**Comment by MrWhiski** [comment]
Thanks for the response. 
I figured out that it was my fault. I tried to put all the models from my rails project in it. Then I wanted to realize the 1 to 1 relation in the database, seems like I produced some sort of infinite loop. I realized later that I dont need all my models in the documentation. So I guess I am good for now :)
