### ISSUE TITLE
multi-line description converted to quoted string and GFM table does not work

### ISSUE THREAD

**Issue by vnalla** [swagger-api/swagger-editor#785]
the multi-line description field in info and operation object is defined with desription: >- and/or description: |-. First time saved using "Download YAML" save correctly. But when i read in to editor again using "Import File", the editor converts it to a "quoted String" - which is difficult to edit/update. Why can not it preserve with the new lines. Note: I have replace the special char's in the description content lile & with &amp; and : with &#58;.

if include table in description field it is displayed simple text not as table.

**Comment by webron** [comment]
Can you provide an actual sample that exhibits the problem and would help us to test?

**Comment by vnalla** [comment]
Hi,

I have edited the original files to keep the minimal stuff. If you look at the description field in info object of both swagger.txt, and swagger2.txt - the description fields are not quoted strings. However as soon these files are imported file->Import File in to swagger editor they become quoted strings as shown in the swagger.png and swagger2.png respectively. if I save the files again using File->Download YAML the quoted string is saved and it becomes painful to edit after that. However the description in the get method stays intact. 

I had to rename the yaml files with txt extension to upload.
[swagger.txt](https://github.com/swagger-api/swagger-editor/files/99987/swagger.txt)
[swagger2.txt](https://github.com/swagger-api/swagger-editor/files/99988/swagger2.txt)



![swagger](https://cloud.githubusercontent.com/assets/11826854/12496404/8319a22e-c063-11e5-877a-034b722288ef.PNG)

![swagger2](https://cloud.githubusercontent.com/assets/11826854/12496405/831e2880-c063-11e5-96a3-85b9bdd555a5.PNG)

**Comment by vnalla** [comment]
the result are same even if I use description: > or description: | or description: |-

**Comment by mohsen1** [comment]
Correct way of having a multi-line string is using pipe with nothing after it (`|`)

```yaml
swagger: '2.0'
info:
  version: v2
  title: Address API
  description: |
    Provisioning Service provides following 
     capabilities to provision data needed for Address services.
     
     * Address API
     
     Note&#58; Some notes
```

**Comment by vnalla** [comment]
I have tried that. It is not working. Please the screen shot below.

![image](https://cloud.githubusercontent.com/assets/11826854/12718594/955ce920-c8bd-11e5-8586-c4898d7b85fe.png)

**Comment by saharj** [comment]
This should be fixed now in #750

**Comment by vnalla** [comment]
Hi
I downloaded the latest swagger-editor v2.9.8 and still see the same issue.

thannks

**Comment by saharj** [comment]
@vnalla It is fixed on master

**Comment by vnalla** [comment]
I know this is no correct to report other issues. But the master build is broke the editor is erratic, like the cursor jumps, URL's in $ref are not resolved etc. The files were working fine in the v2.9.8.
