### ISSUE TITLE
paste JSON not working

### ISSUE THREAD

**Issue by gabrielsroka** [swagger-api/swagger-editor#805]
I create a YAML file, save it as JSON, but when I try to paste the JSON, it gives me errors.

**Comment by webron** [comment]
Can you share what errors you're getting? We can't do much with that info.

**Comment by gabrielsroka** [comment]
trivial example (but you'll get an error)
1. go to editor
2. File / New
3. File / Download JSON
4. open downloaded file, copy contents
5. File / Paste JSON, paste contents
6. get error:

Error
Object
message: "options.definition is required"
code: "UNCAUGHT_SWAY_WORKER_ERROR"

or [swagger.json.txt](https://github.com/swagger-api/swagger-editor/files/113181/swagger.json.txt)

**Comment by saharj** [comment]
I can not reproduce this issue. Maybe you are using an old version of Swagger Editor.

**Comment by juanlu91** [comment]
+1

**Comment by malim360** [comment]
I have the same problem. 

Same error with sample files.

**Comment by gabrielsroka** [comment]
I'm using your website.

**Comment by webron** [comment]
@saharj - I was able to reproduce the problem with the online version.

**Comment by saharj** [comment]
My bad! There is an error.

**Comment by saharj** [comment]
I just made a PR to fix this.

**Comment by SEWilco** [comment]
I'm sill getting that error at http://editor.swagger.io/#/ when I export a minimal example yaml as JSON, then paste it.

**Comment by SEWilco** [comment]
Also am getting it when I paste from https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/json/api-with-examples.json

**Comment by fehguy** [comment]
Please try clearing your browser cache.  I've seen that cause trouble with spurious errors.

**Comment by SEWilco** [comment]
Clearing browser cache doesn't help (in Chrome browser on Windows 8.1).
I also can't import a .json file -- after selecting the file the import button is still locked.

**Comment by saharj** [comment]
@SEWilco This issue has been fixed and will be published on next release very soon.

**Comment by SEWilco** [comment]
@saharj Thanks. I'm just puzzled how it was ever broken, as any project using JSON as their standard should have noticed.

**Comment by karishay** [comment]
Has this fix been pushed? I'm still getting this same error, pasting or uploading a file.
